# Generated by Django 6.0.1 on 2026-01-07 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HazardReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('A', 'Catastrophic'), ('B', 'Hazardous'), ('C', 'Major'), ('D', 'Minor'), ('E', 'Neglible')], max_length=1)),
                ('probability', models.IntegerField(choices=[(5, 'Frequent'), (4, 'Occasional'), (3, 'Remote'), (2, 'Improbable'), (1, 'Extrememly Improbable')])),
                ('risk_level', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10)),
                ('risk_tolerability', models.CharField(max_length=50)),
                ('contact_info', models.CharField(max_length=255)),
                ('immediate_actions', models.TextField()),
                ('recommend_actions', models.TextField()),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Reviewed', 'Reviewed'), ('Closed', 'Closed')], default='Submitted', max_length=20)),
                ('supervisor_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
