# Generated by Django 5.0 on 2026-01-08 07:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hazardreport',
            old_name='recommend_actions',
            new_name='recommended_actions',
        ),
        migrations.AddField(
            model_name='hazardreport',
            name='reporter_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hazardreport',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hazardreport',
            name='probability',
            field=models.IntegerField(choices=[(5, 'Frequent'), (4, 'Occasional'), (3, 'Remote'), (2, 'Improbable'), (1, 'Extremely Improbable')]),
        ),
        migrations.AlterField(
            model_name='hazardreport',
            name='severity',
            field=models.CharField(choices=[('A', 'Catastrophic'), ('B', 'Hazardous'), ('C', 'Major'), ('D', 'Minor'), ('E', 'Negligible')], max_length=1),
        ),
    ]
